// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihmJAvi66LbebOJOCZFkopYzxiVchgSY',
    appId: '1:764090658264:web:40fedae4f38d6a86ae16ad',
    messagingSenderId: '764090658264',
    projectId: 'first-36b89',
    authDomain: 'first-36b89.firebaseapp.com',
    storageBucket: 'first-36b89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmwXc_jY-5p15dPfrD39iAjv_QG7bYHfk',
    appId: '1:764090658264:android:e2f1a3dc28e3f158ae16ad',
    messagingSenderId: '764090658264',
    projectId: 'first-36b89',
    storageBucket: 'first-36b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_-1gSJ1TaWo3qU-VtXsi6PRx857QXPo',
    appId: '1:764090658264:ios:e2ff3f680b998a16ae16ad',
    messagingSenderId: '764090658264',
    projectId: 'first-36b89',
    storageBucket: 'first-36b89.appspot.com',
    iosClientId: '764090658264-vnnta3mrps7767752975ocgm5m2kc9bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb_-1gSJ1TaWo3qU-VtXsi6PRx857QXPo',
    appId: '1:764090658264:ios:e2ff3f680b998a16ae16ad',
    messagingSenderId: '764090658264',
    projectId: 'first-36b89',
    storageBucket: 'first-36b89.appspot.com',
    iosClientId: '764090658264-vnnta3mrps7767752975ocgm5m2kc9bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );
}
